### PR TITLE
Paf

### PR DESCRIPTION
**Pull request by AkRampersad**
This is the initial pull request for Population Allele Frequency.  The implementation in this PR has all of the annotation modules and information in a single Genomic Annotation Observation.

### CODE REVIEW

**Comment by sirkyp** [comment]
@AkRampersad - You will want to talk to @rhdolin , after a conversation today, we are going to propose this be deferred to the next release of the IG.

**Comment by AkRampersad** [comment]
I am more than happy to make sure this is done right the first time.
Please let me know what needs to be done and I will see to it as soon as
possible. I hope the work was up to par.

**Comment by sirkyp** [comment]
@AkRampersad - for now, I switched this PR to 'Draft' so that it would be harder for anyone to mistakenly merge it. We can leave it in draft for now, but assuming the WG decides to defer this request, we can probably close this PR and delete the branch.
cc: @rhdolin

**Comment by sirkyp** [comment]
The associated JIRA has been defered, so I am closing this PR.

**Comment by sirkyp** [comment]
@AkRampersad - Is it OK to delete this branch? I don't want you to lose work, but I would like to delete branches are not working with.

**Comment by AkRampersad** [comment]
Yes it is okay to delete! I have stuff saved locally so my work will still
be there if needed. Thank you very much for asking.

**Pull request closed without merging**
