### PR TITLE
Without grouper

### PR DESCRIPTION
**Pull request by sirkyp**
PR for:
FHIR-32423
FHIR-32095

### CODE REVIEW

**Comment by bheale** [comment]
looks to me like the conflicts can be resolved by including the text from patricks branch and this one

**Comment by bheale** [comment]
I resolved the conflicts. They were removing the grouper profile from the FSH file and an addition to the general page of a paragraph

**Review by bheale — APPROVED** [review]

**Comment by sirkyp** [comment]
@bheale - Wanted to ensure you were aware that I made some QA fixes after you approved, wasn't sure if you wanted to review again or not.

**Comment by sirkyp** [comment]
@bheale - Feel free to push another commit if you found some other commented out areas (commented out with this branch of course)

**Comment by bheale** [comment]
I know there there as I commented them out.

**Pull request merged**
